### ISSUE TITLE
`private (set) state: State`

### ISSUE THREAD

**Issue by dev-yong** [nsoojin/VoiceControlSample-iOS#1]
https://github.com/nsoojin/VoiceControlSample-iOS/blob/e09372aacf3aa2c87009af5c0220c20f7ca19af9/VoiceControlSample/VoiceControl/VoiceStateView/VoiceStateView.swift#L15

지난 세미나를 매우 흥미롭게 보아 코드를 보던 중, `state: State`가 private set이 되는 것으로 보여 질문드립니다.
외부에서`stateView`의 `state`를 확인하기 위함으로 보이는데, `stateMachine`에 있는 `currentState`를 이용한
```swift
internal extension VoiceStateView {
    enum State: RawRepresentable {
        
        case attending, detecting, listening, processing, reporting
        
        var rawValue: GKState.Type {
            switch self {
            case .attending:
                return AttendingState.self
            case .detecting:
                return DetectingState.self
            case .listening:
                return ListeningState.self
            case .processing:
                return ProcessingState.self
            case .reporting:
                return ReportingState.self
            }
        }
        
        init?(rawValue: GKState.Type) {
            switch rawValue {
            case is AttendingState.Type:
                self = .attending
            case is DetectingState.Type:
                self = .detecting
            case is ListeningState.Type:
                self = .listening
            case is ProcessingState.Type:
                self = .processing
            case is ReportingState.Type:
                self = .reporting
            default:
                return nil
            }
        }
        
    }
}

...

var state: State? {
        guard let currentState = self.stateMachine.currentState else {
            return nil
        }
        return State(rawValue: type(of: currentState))
}
```
이와 같은 로직은 어떻게 생각하시는지 혹은 private set에 대한 다른 의도가 있으셨나 질문드립니다.

**Comment by nsoojin** [comment]
현재 코드랑 비교해서 (1) 스위치 문이 하나 더 늘어나야하고 (2) state가 옵셔널이 되는 점이 단점으로 느껴집니다. 반면에 해당 코드의 이점이 무엇인지 잘 이해를 못하겠는데 설명 해주실 수 있을까요? ㅎㅎ
광용님 말대로 외부에서 현재 상태를 확인하기 위함입니다. state를 바꾸려면 `func setState(_ state:)->Bool`를  써줘야하고요.

**Comment by dev-yong** [comment]
`stateMachine.currentState`와 `private (set) state`의 값이 다를 경우에 대한 가정을 하다보니 위와 같은 생각을 하였습니다. 
수진님 말씀처럼 `func setState(_ state:)->Bool` 를 통한 값의 변경이 일어나니 큰 이슈는 생기지 않겠군요.
답변 감사드립니다.

**Comment by nsoojin** [comment]
아 네ㅎㅎ computed property를 써서 그런 경우를 원천 차단 하고 싶으신거군요. 

제 구현은 그런 위험이 있을수 있으나 현재는 `func setState(_ state:) -> Bool` 여기서만 값 변경을 하도록 구현을 함으로써 사이드를 최대한 통제하고, 약간의 위험을 떠안는 대신 스위치문을 없애서 코드가 좀 더 간결하고 옵셔널을 없애서 클라이언트의 고민/번거로움을 줄여줬다고 볼 수 있을 것 같습니다.

좋은 의견 고맙습니다
